apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx-controlled-nvme-bench-3r
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    storage.compaan.io/benchmark: "true"
    storage.compaan.io/backend: longhorn-rwx-controlled
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  diskSelector: nvme
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  shareManagerNodeSelector: kubernetes.io/hostname:fordyce
  shareManagerTolerations: drbd.linbit.com/lost-quorum=:NoSchedule
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
