apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-rehearsal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  source:
    repoURL: git@github.com:rochecompaan/homelab-k8s.git
    targetRevision: main
    path: argocd/homelab/forgejo/rehearsal
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo-rehearsal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
