---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: copyparty-config
  namespace: jellyfin
spec:
  encryptedData:
    copyparty.conf: AgBlS4x07wohkhlV1OTCK0r2YCzdcPKA4j6cQmIch6mkvHeYL8z9/uS9CHcqtGlTpWqD+oMmnyqciG4K4+cYKsx54l/WYbCZ+Pr1V6JxT0b+2O4SxJZR1pvhxLNTps5yfUOsPeElcQgiBqTNKcQtjANcqsyqCbX5d2q2M1MaEQGBSCQP1EyvAEtwBAaGBQcS86u7OGLzfIhwTmNw4tnPNOZTeLHw57bLfpemDbm3VKFDLr84VzS/zQJKuWQpi12SjPZHgLARE2g0J7Ywd0T09F+x9W3Z0SLibXP3lnIWYauuaAls8W3grc/ycDCaVInGfhdwl/nRhioxxyPWcBjFmRo71vQyR6r1Rf+V4rsYN3LLPfsozYF8BbORmhXowLO7t8jABJ6ylgTfu+zhICh9U+k1L0p/WRMohkBVq7Di2Z4IOl6bUEdJeabIIhi4ag+R75bsG5OL7MyfGjFJqATR57eyk3w7OOqWRXeEBrxIVM34EKVXqamcTiWbk2YuLgmh4vyUuphEyAK+pPJ0WjIxmll3g4th3LZpbEaTnFQzMg/v53hxxLm5NCcbFiPgYoalgYJ3s0i/FZ4W9QaADEMxcjKPcUxXljjQ5usX7m5DKd9NXiAA754Fw2whTQQXKzkH0sio6AZiC9AAqeVzZu1yMRGkCxCIzerBzVXn546waJx8UjtUA1B7uwdP4ZQlEmoa17n7GEdeKCut1Yd/E9ujn3vVqrG4dtCbDDNCGVtE/gDEFOrvthN+uDcqobj5Y1eujCndLG2Up/uOsNNZ0bKX41plWeqAoZE99JwuKDpDl1AYZuPk12b/OAGCffqppJMXFvi/zLR1HRsd+zMMsDJ50lSkEim77TawbtjKidW2QN2TXU/p8XkFwjF0jXJEtzWd9KaMn69zjc03lh09yaoWT9lSkvzaUPoxQRRFhhTDYD1VnZ/HpUslxS/Qj2LGk9+84itzpRKUeOUK3xFlOCGxR1S1lzN7pj0UGsmiNqHFcavsDesioxixbZ1ba/P+O4VQ9UbWN03Z4PeCLOvkUrO0sXz2AC5kLeuZys3HIoqRD8q4w4rX491dtoh91SqkDdmb4Tlr/TAKuGZ9MBQvtuJau4Kvo6O5Zvu913K9ZIYtb6HWlGZYiTvMLLw3bYih5lSV9zTMeT5TKXOwW0Rt8N+zBP20hDKKDaj7vSEknfPHYpCXyP21MA6/lOytvtbR7s/g3MmgiebVKqxRS4TH6S02aT5S5+Zl4MnlA1hwY7Nj2OOcQFhVt8s4VGa8EFuFP92RPcb+psPDzk0IIVy3rGi7hRM6R3oumVN8gOl0vgUtnlnZBcPf
  template:
    metadata:
      name: copyparty-config
      namespace: jellyfin
