apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty-config
  namespace: jellyfin
data:
  copyparty.conf: |
    # -*- mode: yaml -*-
    # vim: ft=yaml:

    [global]
      e2dsa  # enable file indexing and filesystem scanning
      e2ts   # enable multimedia indexing
      ansi   # enable colors in log messages
      ver    # show version
      xff-src: 10.42.0.0/16

    [accounts]
      roche: brightred

    [/]            # volume at webroot
      /w           # share /w (the container data volume)
      accs:
        rw: *
        rwmda: roche
