apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - copyparty-config.yaml
  - pvc-media.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - copyparty-service.yaml
  - jellyfin-ingress.yaml
  - copyparty-ingress.yaml
