apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-piper
  labels:
    app: wyoming-piper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wyoming-piper
  template:
    metadata:
      labels:
        app: wyoming-piper
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: piper
          image: rhasspy/wyoming-piper@sha256:69b7f797ae3a8c3c0202cbf97152fb795d78c2355de2a31655c20671247360d8  # yamllint disable-line rule:line-length
          imagePullPolicy: IfNotPresent
          args:
            - --voice
            - en_US-lessac-medium
          ports:
            - name: wyoming
              containerPort: 10200
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          startupProbe:
            tcpSocket:
              port: wyoming
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: wyoming
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: wyoming
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wyoming-piper-data
