apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
spec:
  type: ClusterIP
  selector:
    app: wyoming-whisper
  ports:
    - name: wyoming
      port: 10300
      targetPort: wyoming
      protocol: TCP
