apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postiz-temporal
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      postInitSQL:
        - CREATE DATABASE temporal_visibility OWNER temporal
