apiVersion: batch/v1
kind: Job
metadata:
  name: piraeus-finalizer-cleanup
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus-finalizer-cleanup
    spec:
      restartPolicy: Never
      serviceAccountName: piraeus-finalizer-cleanup
      containers:
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.33.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /scripts/cleanup.sh
          volumeMounts:
            - name: cleanup-script
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: cleanup-script
          configMap:
            name: piraeus-finalizer-cleanup-script
            defaultMode: 0555
