---
apiVersion: ziti.sixfeetup.com/v1alpha1
kind: ZitiAccessPolicy
metadata:
  name: postiz-dial
  namespace: ziti
spec:
  type: Dial
  identitySelector:
    matchRoleAttributes:
      - admin
  serviceSelector:
    matchNames:
      - postiz
