apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshot-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.4.0
    path: client/config/crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
