apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
  - probe.yaml
  - snapshot.yaml
  - pvc.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - runner-registration-secret.yaml
  - runner.yaml
