apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-rehearsal
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
