---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-rehearsal-runner-registration
  namespace: forgejo-rehearsal
spec:
  encryptedData:
    token: AgAzEnGqxKPVaazzpF37ou5UWcJ3HcVOIUPu7OUa/u9iC9LgiZD/wJY3gIC+Xb/HPjJ6FE/GG5CpTddNdKVCAuI+yBZ3+TBJ9DEbQvv6K7xkpHzPOHt7ld+6N6647Mil+pasN64746R45ebtIKK09fTpGbxDUQolt4N2CzYaSfLakpPpuo4ghHw/Me8WNSUqkCmH8g+yeY/OfGu8iIk89sSJYsavvGE9v3ned1spDXzeZuKasLEUQwXw4XR9pTvy0qdQQpHwXY8Z2RTXVWnNXlIqmN/tQnNMBDdbX1TmjOhhp0Ee6TA2HrMjjtpGjIh0hNf5vHCEFyQCUxQ6xme66r8m4IxlJDwOeaT8GsRpCCn9PXT/OJgtg4GbJRVu353h1NgA7baxnAHv+XbZEarVvV85ALWCUJJAdgtzU2ffZKHiU7bwQ+LhDWIow+7cFkILseOx6Wm5HZiwEzPRfsDn8U5C6cMVyYH1tnuM6552vbcjIwJlTzjoSRbeLivR26Z+Ik6FxLYVtycRKKssIYGEgogpGeIWn03oJabtO75fs5Xl9jUIHQ/rOHWN9Uf9VDhr6Sli5Ua2tl4QbR/0kEKAEfKXz8boC/2qWo2bYyklucWoP3r9VpVI7cUp3dFbSaDb6OuJXp3eD2oV09+Om/rAVe9XTUURUT3yMfvvqsTkAnFR3JansS8zEhfwnxYgx9Vtbm4OLsQveUhsBv+BMwPybfMgKqJCgsruWmL19KKpkLoL7SdyMGTvgvSec0Bn
  template:
    metadata:
      name: forgejo-rehearsal-runner-registration
      namespace: forgejo-rehearsal
