apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: piraeus
    repoURL: ghcr.io/piraeusdatastore/piraeus-operator
    targetRevision: 2.10.7
    helm:
      releaseName: piraeus-operator
      valuesObject:
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: piraeus-datastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
