apiVersion: v1
kind: Secret
metadata:
  name: piraeus-operator-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: ghcr.io/piraeusdatastore/piraeus-operator
  enableOCI: "true"
