apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: harbor
      owner: harbor
