---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-oidc
  namespace: harbor
spec:
  encryptedData:
    CONFIG_OVERWRITE_JSON: AgA0FkEUzj5Fqz1YQsUBkUw8CcaJzdLgqOPGeBEINlJrs1C5ilVjaFjXWF8+Cjt9mKUPhRfHTC/fDu359KqTzLDXK6WkdLLWVORw89V2cbZfvfhs8SU3oEO4YSFLbGVr0I85BruaF5RWx7XV4qqvjb5IxK4ZYVTH+/33o4SaKssMBYqtlXN5KWu7wfFd/8V/A8BmDMJdr0pYqdPP1coKGLWm89j32nJNYLt+vfnH9aL/PIeV84T/VD89ML+Eot1Qlue5g3bu4r+2fp3J5X4rK/qWGFSDRQA7tyDWR+y1EoeHA6qlWXIsC+MWA2bj/gjtPzTEaEyFL+uhserb7hRRGKccvC+d41wngy2SDO5ldtfzOHhEkirsrp7TVe8s1UVnlMiaAUIhR3BVst254/lliHCZ9gFWtWAJjEWncbTQW7yTfggITipBMNFZW1Tvemz4+Jj7g1h7RmdhRKsw92XdC8hMLr9i+GXR8bNICyybU4fLVaTLGrZCqOZlyaYKc9Xz/P3nF63PYUxFPH/49i5Tkzmn2GCclLPOIjQG8nTnRtAG1fYL8tHNbCtvOJUyano8+ugTGJOl2lvpndiiP9Ys/tSLyJbmIo4AnQqvRFvm5Qqosq+QiuuN4bzi+TZUDMcVCebwwE9Kq/ntotEiHiVsmmBzO2aSSUQiSRMObE/aIrQ0TmEynBTqkh0Eqs0f1TX6YKmTROnz1UB/vZ9qCDHhzQzd0Lh2wThms9iX1UuIUGT8XTWztHQx9WWuxY7Odk75Ns7X3oF7LQQFlMahSjrednwwxcS0SVe+z8zfxZlChGHST/LbjK3sZPz1uT5b9yj3VqmRLm5aHJYfo3l0tV1Sz6iO6h6pnFZ1Hra4Fd1R/3WnRaQkRpVvnCgnPzWL5k4+3fEL+gujN0IYJOqyLKWMuOq4ZYMYiWt07NqgddS+jY56TNe2mQfhZmBdWWEZnVMC27IJQpWMz+oP6yVxtd3q90crbe5AizGfpKCTkFSU9JUt9vwhYB7enUxRgZ8fbO8tBjDhd81OpqjBloFA0HLvVOeDNfamw28vcWH3FCWKAFaiQV+9huLGTPTF5Jo3fWYlCoXsfhOpF2Xv/QxIypCPSa8nkHzRWQZQTYYwllq6xpXJnMjOwQl7tsfdx0A8yhoeHbEtf1MXUdX59rnOb+R3YBtm9fZD3KdHi5k/eLM+LLlJiLSG+Yh/NSIDdCk8PFbAD3V55eB+8HBsnagNKVfR0EqEjLTTSwGlP+ihQCJWYX+hnFtxUqLn/pJQxkX7aW8oVgG0hM7CV1ahSj7Sdd2smhDtuKTBCIzU
  template:
    metadata:
      name: harbor-oidc
      namespace: harbor
