apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - harbor-cluster.yaml
  - harbor-registry-pvc.yaml
  - harbor-ingress.yaml
  - harbor-secrets.yaml
  - harbor-oidc.yaml
  - harbor-token.yaml
kind: Kustomization
secretGenerator:
  - name: harbor-ca-bundle
    files:
      - ca.crt=compaan-ca.crt
generatorOptions:
  disableNameSuffixHash: true
