apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  source:
    repoURL: codeberg.org/wrenix/helm-charts
    chart: forgejo-runner
    targetRevision: 0.7.6
    helm:
      releaseName: forgejo-runner
      valuesObject:
        knownLastVersion: true
        replicaCount: 1
        runner:
          config:
            create: true
            existingInitSecret: forgejo-runner-init
            file:
              runner:
                capacity: 1
                env_file: ''
                envs: {}
                labels:
                  - ubuntu-latest:docker://catthehacker/ubuntu:act-latest
                  - ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04
                  - docker:docker://docker:29-cli
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
