apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-finalizer-cleanup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '6'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:rochecompaan/homelab-k8s.git
    targetRevision: main
    path: argocd/homelab/piraeus-finalizer-cleanup
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
