apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nvme-disk-tagger-serviceaccount.yaml
  - nvme-disk-tagger-rbac.yaml
  - nvme-disk-tagger-configmap.yaml
  - nvme-disk-tagger-job.yaml
  - storageclass.yaml
  - pvc.yaml
  - fio-script-configmap.yaml
  - writer-job.yaml
  - reader-dauwalter-job.yaml
  - reader-selassie-job.yaml
