apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nvme-rwo-strict-pvc-run-001
  namespace: storage-benchmark-rwo-strict
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: storage-benchmark-rwo-strict
    storage.compaan.io/benchmark: rwo-strict
    storage.compaan.io/backend: longhorn-nvme
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme-rwo-strict-3r
  resources:
    requests:
      storage: 20Gi
