apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piraeus-fio-pvc
  namespace: storage-benchmark
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: piraeus-bench-3r
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
