apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-benchmark-rwo-strict-longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:rochecompaan/homelab-k8s.git
    targetRevision: main
    path: argocd/homelab/storage-benchmark-rwo-strict-longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-benchmark-rwo-strict
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
