apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-fio-pvc-v2-run-001
  namespace: storage-benchmark-v2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: storage-benchmark-v2
    storage.compaan.io/backend: local-path
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
