apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: mayastor-rwx-bench-dauwalter
  namespace: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  node: dauwalter
  disks:
    - aio:///dev/disk/by-id/dm-name-vg--nvme-mayastor--bench
  maxExpansion: "1x"
---
apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: mayastor-rwx-bench-fordyce
  namespace: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  node: fordyce
  disks:
    - aio:///dev/disk/by-id/dm-name-vg--nvme-mayastor--bench
  maxExpansion: "1x"
---
apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: mayastor-rwx-bench-selassie
  namespace: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  node: selassie
  disks:
    - aio:///dev/disk/by-id/dm-name-vg--nvme-mayastor--bench
  maxExpansion: "1x"
