---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    rpcSecret: AgCKHV4ak5+e34lo6+sI0LzE86iHU+TBONMtNLRP+yaW7gleRFRpuvPHlaL57RDkqu3JW0lK6NaXDPnDTrAOcysS01bHmMkXn+Oo8y0u6YKNQ/jlZnGL/Hd35+ylkAga/6/DKQ85PUY13PllmeMlxDYH9YJBYvCsbgigZ8tJYVi4egWroXfJKE/LqmiI3LobiQ71ampWixuHkL4OEMzU6oGHpw+cNhTxnBIHvews0POx3MsISj1XQrznvpZNbwTz+MPljsu1/WYH1I+DBqCA3cXGUiuIdMp2J8E1osx/vmHE33rF2cdvkKLoC4UOXOuP3xtnzbcRBT1kRn5sPaI/42UWXRkQ/nfWZ9uKLMxs9S0JtMhjiIefa+T+9IyTJaIu3k8q4txG1SuUjS23WZUHgGia5oj+SnF8gg/gzR6NFZE8lanrkGZiVdLZ51cxylkEhjy66dBq+kZQjRLINazXbreMxwMpXL0I+Wae7K3PBHCvZ+2d59GsKFWr11gZTSRafX9z57lMVlz7tDYfB5Xh2a8vBAdFeIDX4Pq6MEDUaZUIBBy8w/Ybx0e0gujknOS3nCedQSfPrfHbcolg35tR+vaiq7Xj2wc9vSuQ0244ATNC46shgjCd5rzhgUKMzqr4Gd0Hm5O29gjfFolc64D3Y5xWRa0igAP+lMszA7oMK3gD+I3fb5i3Qmosidj6UdnMa9QLLC+NlcPQvVaI9Ee/MZvtRKaZdeEQCm7k1VOKOd6F2kuwXJM9hmH+ZNsshk/UVhpKXC4zavctTQt2DUuVSAYO
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      name: garage-rpc-secret
      namespace: garage
    type: Opaque
