apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-whatsapp-config
data:
  config.yaml.tpl: |
    network:
      os_name: Mautrix-WhatsApp bridge
      browser_name: unknown
      displayname_template: '{{or .BusinessName .PushName .Phone .RedactedPhone "Unknown user"}} (WA)'
      call_start_notices: true
      identity_change_notices: false
      send_presence_on_typing: false
      enable_status_broadcast: false
      disable_status_broadcast_send: true
      mute_status_broadcast: true
      initial_auto_reconnect: true
      history_sync:
        max_initial_conversations: -1
        request_full_sync: false
        dispatch_wait: 1m

    bridge:
      command_prefix: '!wa'
      personal_filtering_spaces: true
      private_chat_portal_meta: true
      async_events: false
      split_portals: false
      bridge_status_notices: errors
      bridge_matrix_leave: false
      bridge_notices: false
      relay:
        enabled: false
        admin_only: true
      permissions:
        "*": relay
        "matrix.compaan": relay
        "@roche:matrix.compaan": admin

    database:
      type: postgres
      uri: ${DATABASE_URI}
      max_open_conns: 5
      max_idle_conns: 1
      max_conn_idle_time: null
      max_conn_lifetime: null

    homeserver:
      address: http://matrix
      domain: matrix.compaan
      software: standard
      async_media: false
      websocket: false

    appservice:
      address: http://matrix-whatsapp:29318
      public_address:
      hostname: 0.0.0.0
      port: 29318
      id: whatsapp
      bot:
        username: whatsappbot
        displayname: WhatsApp bridge bot
      ephemeral_events: true
      async_transactions: false
      as_token: ${AS_TOKEN}
      hs_token: ${HS_TOKEN}
      username_template: whatsapp_{{.}}

    matrix:
      message_status_events: false
      delivery_receipts: false
      message_error_notices: true
      sync_direct_chat_list: true
      federate_rooms: true
      upload_file_threshold: 5242880
      ghost_extra_profile_info: false

    provisioning:
      shared_secret: disable
      allow_matrix_auth: true
      debug_endpoints: false
      enable_session_transfers: false

    public_media:
      enabled: false

    direct_media:
      enabled: false

    backfill:
      enabled: false

    double_puppet:
      servers: {}
      allow_discovery: false
      secrets: {}

    encryption:
      allow: true
      default: true
      require: false
      appservice: false
      msc4190: false
      self_sign: false
      allow_key_sharing: true
      pickle_key: ${PICKLE_KEY}
      delete_keys:
        delete_outbound_on_ack: false
        dont_store_outbound: false
        ratchet_on_decrypt: false
        delete_fully_used_on_decrypt: false
        delete_prev_on_new_session: false
        delete_on_device_delete: false
        periodically_delete_expired: false
        delete_outdated_inbound: false
      verification_levels:
        receive: unverified
        send: unverified
        share: cross-signed-tofu
      rotation:
        enable_custom: false
        milliseconds: 604800000
        messages: 100
        disable_device_change_key_rotation: false

    env_config_prefix: null

    logging:
      min_level: info
      writers:
        - type: stdout
          format: pretty-colored
