apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-whatsapp-postgres
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: mautrix_whatsapp
      owner: mautrix_whatsapp
