apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayastor-fio-pvc-v2-run-001
  namespace: storage-benchmark-v2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: storage-benchmark-v2
    storage.compaan.io/backend: mayastor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-bench-v2-3r
  resources:
    requests:
      storage: 20Gi
