apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.4.0
    helm:
      releaseName: traefik
      valuesObject:
        service:
          type: NodePort
        ports:
          web:
            nodePort: 30080
          websecure:
            nodePort: 30443
            transport:
              respondingTimeouts:
                idleTimeout: 300s
                readTimeout: 300s
                writeTimeout: 300s
          mqtt:
            port: 1883
            expose:
              default: true
            exposedPort: 1883
            protocol: TCP
            nodePort: 31883
        deployment:
          kind: DaemonSet
        providers:
          kubernetesIngress:
            ingressEndpoint:
              hostname: traefik.compaan
            publishedService:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
