apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piraeus-rwo-strict-pvc-run-003
  namespace: storage-benchmark-rwo-strict
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: storage-benchmark-rwo-strict
    storage.compaan.io/benchmark: rwo-strict
    storage.compaan.io/backend: piraeus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-rwo-strict-3r
  resources:
    requests:
      storage: 20Gi
