---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-authentik-oidc
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBpIrfgb/cuEUYeYBYpeiy2FhQlXAkXfhy/lpl2N4yGwnduw65BDNTJiSfldosGZg4fn6BRmd5d+6RzR12cppT2feQA/SMkBCuJ1bDL0urooKGSTdJykxwlNWpPb8vQwQ5fnErp2KOaVUKcJ8VnICirSt+NU6gz4c3o6rhvNH1OwZ2fN8PuyieQGsEWSt94hOMgXPSD6Ui6T/ao7q8o5jXKY3zcAU9M00THjVNrDiN2y9TnzEVSKAeGOn2I4SXPNruGENxlp5ioV8xmkGO0g6y65izWHNe7uXgurOto8YZZQM6SETl+9qCTTzk2zuj4IMmDlF723++RHigmHIQTy/hspfqVxFXEDxsvy3vfpYE2DF+yNMH34Jz7lkEVjWW0sA5XiLSc+boipgOTWsiRt2hNsA9c53rQU376/8RcX4zqiozPLvaXVFEYr4MMPc+OUsMN3aGt+XekbB1jlAwe+TmB1xBVdrdS6gUpvHKCznmQ0cdQuJkqjs7wotdbTvYvEAyk/GeDcakT2qIJkbC6lGCOFE31RMrz9rVFxmR9GJLb6rF7SIdZAO31qBKok+MLPT03wBc9NS0n7hpFGElMmc5LH/qobvDxdRIUNJmZHJ+SdCz0mXnlKhJHZ3TdgSsn99QtvzTR3mXZ9reS4LdRfAOl/Me/64SCyFkbjm0fbr5mpgEtPwntg61rf5sORvnshPRmYwjx7c8mL+p0cfaVkhA86U6eAiZCDHGsNCIn77/tAv1FLLekT+T2KzcviaahhSHtNql/9JDxOcE4geetZZrO+FNaTja/+8eep/3Z01pA5bSMyWdS9Goso4w+zjfbau45Kdhdss+J9qm3OHoOak92VpigHhyARtcUCP7LaW1s0Q==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-authentik-oidc
      namespace: argocd
