---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-authentik-oidc
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBjWVCIGiwflt9gkkbsKEURfMRnBlHhVHqDOIOZPOUvkSaeRMi+VtMQZQ61y4PV+6m6ddHBzfIfdMAD7GpYSpUaySZnQc6OThvpIjoAUAtt8w4DO/A6hV5uhIc8mx7sz/U3FJs1tWVMi3R+OcBn47zkzy19HDjYyF+tGALMRP4O+vd6bIenNGk4Ysobic3ESbdLCn9sB4txEUTLebXNr/9S85VcB7yfobYDpcBmztx4AWlsvMoTtJwT/oVIOd/eeK3Rczk8d1ADZeib+76GIhhe6WKzQhdUW9scS+Ipo74GMXnfxOxNcdD8nkCf/zYeRGAxQcgkjqMKh+HN7DiSeHq68VilLR7139nI37/hAkiAXW9Rqp1l+AbruqPJXIL7bAUx4uJt5oechbqWUN9KorMZ7gcqmWWKXwgVfNOUG5RScfJ0HMz4iV9U1TFvftAj/AekZ2Oj9u6qJfgJc1DmiUXK1+XPW4oq4wbkJ5R0P6/muk0zR2189XCBpa6ucndqiVl8jW0Aa9i6yc8oHD/N1+uo0QqT/ea969w4j6ixVIQV7SxsTjrGwtjMAvADrgLmZJE+xfDVc3SZ+6/xyT+kxvQCxFrSC54XPooHJNJWilin59HI77kWcPVEJ1+/0qNrQS4qZUThpKP90Qv961SeCcE1RJIz1z3WAFyk/3/BAersTsaOnZ0YSgVJKGsnsQTg2TMxqIL1rNIT/nHFSrVpnAfKGKHT6+Dd8UJ0pt7qMmB3Zr9zyzA9Jgu1l2Y/PxCXf/UbFxjvg5vG5E13tVM/Qktp
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-authentik-oidc
      namespace: argocd
