---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-harbor-oidc
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_HARBOR_CLIENT_SECRET: AgBPxXtClANsbhUaP8+cJWelvbPqFpWs/AQh+wafyKshkE6aKnUBjL9Hs2lZgdPj+8imD5h/YQNCHvUfzUDoXx1rOyrR8iszVqgYVzuZdN75AQijtuEfGeG+cGxNkBsfkXejHjUJIh/JVhpW8R995vfQRfEDHQIedASfR/jkAe4KNAI7X/+bwBK++2TKfCnxhW4lub9VkhobKBxWwg7E//SyhjvxWjcXJA3SwEV2dmhtzmoG09QVXcJDIt+fpoBti5huMAePPsaEJL/je8u3UFfIa3VFYtDfWTpNdUoSTFlx6TlawS8tmmr4q80Uq6xiocHAb71uUJq6QVyCM4JIGLB6RZCBrkxFzzTwiotuqjFUdy7XsjhOCw0x6FBMNlJrMf+veT+ze8/djCiD+uYPjEzb5yGaLp7N07E0Qsjr0yVWyFJGjPZO1ofGOn3rLi0e0ZOetmqvlVNxiHMFdB9NobXnCUtqbHZxJaEl3LkO3aRAxpe3KgRSYa2/LJZW77fX6Gxn2An9ZrZEhmgLZ/oLH0/TxTTveBu4YZlNEfq5Mi9x1q1OV5aHyjSsW0tkb9ZXbwqpCkHSB0j7mU+xfKG1+kkFYC80MUSdByh+5QJ8I9nl86AkESeo/1/L1BQpKssN4oNn0be0QSf/lTgMyKvJQAOdigMA3zbc2j5VrJTcoRg395aJ+dDShenfR0dckXPfjtQVv17hl4Jrsyb/woIPmCJeXOIrOyaa/2fony5FsDC+3XNC0NiSSJqr+HB/OVb+8RYX/8q2tBcqCxRImBbEMnef
  template:
    metadata:
      name: authentik-harbor-oidc
      namespace: authentik
