apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - matrix-namespace.yaml
  - openclaw-secret.yaml
  - matrix-postgresql-secret.yaml
  - matrix-secret.yaml
  - cert-manager-issuer.yaml
  - coredns-configmap.yaml
  - home-assistant.yaml
  - longhorn-sata-storageclass.yaml
  - private-ca.yaml
  - ziti-router-ingress.yaml
kind: Kustomization
patches:
