---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-postgresql
  namespace: matrix
spec:
  encryptedData:
    password: AgC/+aOfio+oTt6GumYvLFIS6bFplN2fQoCDZV9BGzfWDs/uKZH5np0qQkPEotKTupUaZ2MM0uW8rRcT9XwW6BW6IdiDpAGdODm+Ukja590g2+zsJ0+kx5/cYxishMmEPbYJejw8jvw4SHbe7gs5kSBXBanYcpoY3WSVv9YWDC8cv6y2NTegpja7ag2fWyjZhmQ3qZBFSmBlmW4QuagWxQuAiDJ6dHOQYEfauO55BR/y4K0VBpGFaooGDEfuxpMM3CQ9tH800BhRqrN73lS0qjV7opwdyPU36YNGHwJVC/Q2QlFb6wr8ZGs4gaUgmAiWQ6oYxLVeHZoVFNKi5w2ktH3ceyK/un+r4daQ7XYcuGhJsNmecOVzkFp5FNDslYR0Y9Bxm88qR/PD0IG218ym0PgpAPgG4ruRFdKpaeEczaFqixcPwKwSLvd77sHGlEMcueql5c1ySiz0TDcUuhVR68cRSa6QlsUtzMTWUpKfjNzKYnCOSbwkFYMForcSjE4CCu3AVfIx2DvzkkGwrIBYBQYilC8dNkl7179WQBby3+lJSIkGOji/0IYEoTyFwGn6/TAebBw1GnnFEVmiUs/GbMADNvNF3PVErbX1TJdDSJb3NACFZQ6htCFyx4JFyBqRaTlNlaIdbiMkDNSY5yKNrLawtx8/LW6r02YvpFQyyuPMjQlawQ6tc88VUbjW0odlMCr7hKMctKOhKkjI
    postgres-password: AgDCFFviHOHiL7rOIhnE8/GZtk/Ixml8TOpd0+TXdAUh4gzIVcH6XO5AD9UY/ds4yAmmi+T36lMTO/7ufrme+8o2zwD+gX92L5m0FsRgIFplWE1y8Vqvrb/MRSMX59N1gdOPnf+dQOW9eig7pepzWcEG5av2XJ/REEmRypYTzE0jXIIOuwwnrJzjlvMhUN3CwJDjjjjCBpaWfmkQ2O0b2WhfG2V/nk2iz/xuRalBnDcWG6yejGL0NMeH2/32idqykoApIi8eOxV28+E308xRE2yN/47LKWBnBqDaHwg6pGM3Uqa/c0IXCzbE+8yyAB6hlOGHZ960s7mj9KBgHMWUC+HdwxeSZAFtoFIhANXtsrpy+HIUPwZNUbPFkzzqRBfuL1xgLLrVLxBhOqLULZsKvUMKdbNMcl71HZWryynY9havmKWy6/b7U2Skn1aq4s339FLfZAP7v1Lscrb84n4THHN8to71cTHHItVx409a4nsqXnqo6UXqTp8zCUPr3eSTNyPNMLOVziX4aweZh6H64e5iBJ4AajIkz+nJ/IaDpdd4WsnRUyon5Fya2uiL8FcgexGWFdZmXzG9fIJyBa4e7AQ6mDENt6P4QCqwZNiWtuWAyPqDXRk8S3BPKu1yqWyB/AeFeXDfi2OJPGPTdvVvYXTCCZZJxrMxT00yEsUlwzJ5GZf4Q37wm9JCVapq8D4YR1iYSCFUPgUnC+7r
  template:
    metadata:
      name: matrix-postgresql
      namespace: matrix
