apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  project: default
  sources:
    - repoURL: code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: 17.1.3
      helm:
        releaseName: forgejo
        valuesObject:
          global:
            storageClass: longhorn
          persistence:
            size: 10Gi
          ingress:
            enabled: true
            className: traefik-public
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: git.compaan.cloud
                paths:
                  - path: /
                    pathType: Prefix
                    port: http
            tls:
              - secretName: git-compaan-cloud-tls
                hosts:
                  - git.compaan.cloud
          gitea:
            additionalConfigFromEnvs:
              - name: FORGEJO__MAILER__PASSWD
                valueFrom:
                  secretKeyRef:
                    name: forgejo-mailer
                    key: password
            admin:
              existingSecret: forgejo-admin
              username: roche
              email: roche@compaan.cloud
            podAnnotations:
              homelab.compaan.cloud/forgejo-mailer-secret-revision: '1'
            config:
              APP_NAME: Forgejo
              actions:
                ENABLED: true
              admin:
                DEFAULT_EMAIL_NOTIFICATIONS: enabled
              mailer:
                ENABLED: true
                ENVELOPE_FROM: forgejo@git.compaan.cloud
                FROM: 'Forgejo <forgejo@git.compaan.cloud>'
                PROTOCOL: smtp+starttls
                SMTP_ADDR: mail.upfronthosting.co.za
                SMTP_PORT: 587
                USER: forgejo
              service:
                DISABLE_REGISTRATION: true
                ENABLE_NOTIFY_MAIL: true
              session:
                PROVIDER: db
    - repoURL: git@github.com:rochecompaan/homelab-k8s.git
      targetRevision: main
      path: argocd/homelab/forgejo/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
