apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - ../../base/argocd
  - ../../base/cert-manager
  - ../../base/cloudnative-pg
  - ../../base/authentik-db
  - ../../base/authentik
  - ../../base/csi-snapshot-crds
  - ../../base/csi-snapshot-controller
  - ../../base/coturn
  - ../../base/nextcloud-db
  - ../../base/nextcloud
  - ../../base/webmutt
  - ../../base/openclaw-mail-sync
  - ../../base/openclaw
  - ../../base/matrix
  - ../../base/matrix-whatsapp
  - ../../base/miniziti-operator
  - ../../base/garage
  - ../../base/forgejo
  - ../../base/forgejo-runner
  - ../../base/ftp
  - ../../base/infra
  - ../../base/jellyfin
  - ../../base/grafana-postgres
  - ../../base/kube-prometheus-stack
  - ../../base/grafana-dashboards
  - ../../base/local-path-provisioner
  - ../../base/mosquitto
  - ../../base/kyverno
  - ../../base/longhorn
  - ../../base/longhorn-admission-hooks
  - ../../base/openebs-mayastor
  - ../../base/piraeus-operator
  - ../../base/reflector
  - ../../base/sealed-secrets
  - ../../base/speedtest-exporter
  - ../../base/traefik
  - ../../base/trust-manager
  - ../../base/victoria-logs
  - ../../base/ziti-controller
  - ../../base/ziti-router
kind: Kustomization
