apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-nvme-disk-tagger
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: longhorn-nvme-disk-tagger
    app.kubernetes.io/part-of: storage-benchmark-v2
