apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nvme-fio-pvc-v2-run-001
  namespace: storage-benchmark-v2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: storage-benchmark-v2
    storage.compaan.io/backend: longhorn-nvme
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme-bench-v2-3r
  resources:
    requests:
      storage: 20Gi
