apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-sata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-exim-spool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-sata
