---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC+MRseLBU/OQK2TazCMnNDlw25jRKMPde8uLn5al609eGOFvRfTowwaOBW625DmV8zLpO0lJY1iNE6EomLimYQ8sxJguW7OukOu/vc4bWa9mVG9b3cUE1dci4XexxZtgjSi8m/QyaQsT0bRw8qR0l17sZRk7bDKbAx6JSQbBxLl7U43VmQ3RG4z0UPG2rbPOS+YMnaVSvH6s3/3JwXJg+rxs+TBfUI/JDjv5aEJGQqNAucr6U7dy7L8EDcJOFulrjidYaFxTy8uB0BXKbdRmQ4L8MJOnxyghZQQSDNd8TFjXrOloSsVMUfKtk6tkqvMmWd6YEqVWemUeDTnQHB8LBiqpEWWuUBN74HGPV/NHQx4fvkZIG872/v/rz8o0HRzBV1GSGlY2FmDP4TUL/x/EgfUhCe4ockt8ngrmYb3+VXbvKEgYUpcrz7HsDZHryMJ2TqxEc8n2IeCYvAwqPELrZ21UuQnZdweNVNnrnYj52jUBld/yP41MeUyJVl8LmAP/EII7CE/7jV1NxnlKTCKWq9cJ9Ec/85/uEvstmXIccJMn2qQiYTvpuJcYcjpcAAkS7RtPRBmP2nD5ArFFbzluwErz2f8HlHpQkLlOCg49exoPzyQosmPoeVYusTaGKOH4+1szhdNBQ4DOtTGMYofjJBALAr3lPma/pohGeBCv14OoprWT1UgWe4Q16PpRuOxG4hjf8SwW7ZlVIuPt2kTW2qMtwVfbN73t5U5cQQYN3jMjNxAs14lR8P
    admin-user: AgC08hbenY4uEQyKS4HpZtUHL6ekCr6Sl8lpjK4B7nOxmpZ/8FZR9UX+BuDrjGB38biwmpVl+OtT1joaR3O/DDHuiJtuzuKPuYcv97zGDVYB62n0jw5OYM5cajgCMvYPOzNz00XFWLMCm5FoZaX0HZfLlvYy2Via14yucQoimxfytqtRx9Sgve3iaZCF31wmIjcib8yGXRbGEglEumEQMqL1vE0nXi32mO1z8r1ZBIguz9J3NTdVj3IOClSA2N7O65KHH8lJo8DapBhCXUNrFvosijQzf5UF1uBgHNJgvna8CDxS6fXUrDd82aN5CEl5mmUXk/BLsMwybilT+tCZKn+/Z9vVu6QPuMrZfLue2mU+w3hePFQoygBNVh+K8aXJYBznpQ2iCJ3TbrHzUgdMethVSmVQwTlsDJsbqpHWty0UeGD/eWymxZIXEAfhxAn18kKrkNxZndcoa88Uo7lSb5KdAOvaHWcOR+bEGQvli8VTxS3OCApve6Xwa1g4/czjYqhGAo6RrVBanM7i9D2evyvL8kjSn5kZS4y1MNKUPm2n65zWWiJcXDi1mMSK9RPCU3OJeFBey/eaeBzqfbykqLRnNu6+sxOub5ZIdlssucHHtbMrGiIhxpo13YEbx9DjraYnhPbmXu9F1Hy3VLgYV+kaCCfZqWLbQq9OK7hhVPnhNXz6g0TJT4T3jlEDCB3iQYA8LpnI+w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
