apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
